version: '3.8'

services:
  db:
    container_name: db
    image: postgres:13.4
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  init:
    container_name: init
    build:
      context: .
    command: |
      sh -c '
        ./build/wait_db.sh;
              echo "migrations start...";
        goose -dir database/schemas postgres "$${DATABASE_PG}" up;
        echo "...migrations done";
        '
    env_file:
      - ${PWD}/.env.compose
    depends_on:
      - db
    restart: "no"
volumes:
  db-data:
    driver: local
