swagger: "2.0"
info:
  title: Service
  version: 1.0.0
schemes:
  - http
basePath: /
consumes:
  - application/json
produces:
  - application/json

paths:
  /test:
    get:
      operationId: Test
      tags: [Test]
      responses:
        200:
          description: Successful response