// Code generated by go-swagger; DO NOT EDIT.

package app

import (
	apiTest "go-ms-template/internal/generated/restapi/operations/test"

	"github.com/dedovvlad/go-ms-template/internal/generated/restapi/operations"
)

func (srv *Service) SetupSwaggerHandlers(iapi interface{}) {
	api, ok := iapi.(*operations.GoMsTemplateAPI)
	if !ok {
		panic("iapi is not a operations.GoMsTemplateAPI type")
	}

	api.TestTestHandler = apiTest.TestHandlerFunc(srv.TestHandler)
}
