// Code generated by go-swagger; DO NOT EDIT.

package test

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// TestReader is a Reader for the Test structure.
type TestReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TestReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTestOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewTestOK creates a TestOK with default headers values
func NewTestOK() *TestOK {
	return &TestOK{}
}

/*
	TestOK describes a response with status code 200, with default header values.

Successful response
*/
type TestOK struct {
}

func (o *TestOK) Error() string {
	return fmt.Sprintf("[GET /test][%d] testOK ", 200)
}

func (o *TestOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
